Defensive Fix for Client Crash Pertaining a null value in EntityOutlaw.OnReceivedServerPacker
DEFENSIVE FIX FOR CLIENT CRASH
1. While testing with nate, his client crashed with the following error:

Running on 64 bit Windows with 32 GB RAM
Game Version: v1.16.4 (Stable)
Loaded Mods: Unbreakable_Arrows@1.0.0, game@1.16.4, drifteroverhaul@1.0.0, outlawmod@1.1.0, creative@1.16.4, redirectlogs@1.0.0, survival@1.16.4
3/27/2022 3:13:43 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at OutlawMod.EntityOutlaw.OnReceivedServerPacket(Int32 packetid, Byte[] data)

2. We could not repro it either before or after this fix, but it seems like the talkUtil was not being initilized properly in certain circomstances.
3. I changed the initilization to ensure that talkUtil is alway initilized.
4. OnReceivedServerPacket now earlies out if talkUtil is null.
5. This will only ever be a thing when people use vintage story voices.